import 'react-native-get-random-values';
import { v4 as uuid } from 'uuid';
import { format, subDays } from 'date-fns';
import type { Transaction, Budget, SavingsGoal } from '@/types';

const now = new Date();
const currentMonth = format(now, 'yyyy-MM');

export const SAMPLE_TRANSACTIONS: Transaction[] = [
  {
    id: uuid(),
    type: 'expense',
    amount: 49,
    categoryId: 'shopping',
    date: subDays(now, 0).toISOString(),
    note: 'Freepik Premium',
    paymentMethod: 'card',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: uuid(),
    type: 'expense',
    amount: 32.5,
    categoryId: 'food',
    date: subDays(now, 0).toISOString(),
    note: 'Lunch at Thai restaurant',
    paymentMethod: 'card',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: uuid(),
    type: 'expense',
    amount: 15,
    categoryId: 'transport',
    date: subDays(now, 1).toISOString(),
    note: 'Uber ride',
    paymentMethod: 'wallet',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: uuid(),
    type: 'income',
    amount: 4500,
    categoryId: 'salary',
    date: subDays(now, 2).toISOString(),
    note: 'Monthly salary',
    paymentMethod: 'bank',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: uuid(),
    type: 'expense',
    amount: 120,
    categoryId: 'bills',
    date: subDays(now, 3).toISOString(),
    note: 'Electricity bill',
    paymentMethod: 'bank',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: uuid(),
    type: 'expense',
    amount: 85,
    categoryId: 'health',
    date: subDays(now, 4).toISOString(),
    note: 'Pharmacy',
    paymentMethod: 'card',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: uuid(),
    type: 'expense',
    amount: 25,
    categoryId: 'entertainment',
    date: subDays(now, 5).toISOString(),
    note: 'Movie tickets',
    paymentMethod: 'wallet',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: uuid(),
    type: 'income',
    amount: 800,
    categoryId: 'freelance',
    date: subDays(now, 6).toISOString(),
    note: 'Website project',
    paymentMethod: 'bank',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: uuid(),
    type: 'expense',
    amount: 67,
    categoryId: 'food',
    date: subDays(now, 7).toISOString(),
    note: 'Grocery shopping',
    paymentMethod: 'card',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: uuid(),
    type: 'expense',
    amount: 199,
    categoryId: 'shopping',
    date: subDays(now, 8).toISOString(),
    note: 'New headphones',
    paymentMethod: 'card',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
];

export const SAMPLE_BUDGETS: Budget[] = [
  {
    id: uuid(),
    categoryId: 'food',
    amount: 400,
    spent: 285,
    month: currentMonth,
    createdAt: now.toISOString(),
  },
  {
    id: uuid(),
    categoryId: 'transport',
    amount: 150,
    spent: 95,
    month: currentMonth,
    createdAt: now.toISOString(),
  },
  {
    id: uuid(),
    categoryId: 'shopping',
    amount: 300,
    spent: 248,
    month: currentMonth,
    createdAt: now.toISOString(),
  },
  {
    id: uuid(),
    categoryId: 'entertainment',
    amount: 100,
    spent: 45,
    month: currentMonth,
    createdAt: now.toISOString(),
  },
  {
    id: uuid(),
    categoryId: 'bills',
    amount: 500,
    spent: 380,
    month: currentMonth,
    createdAt: now.toISOString(),
  },
  {
    id: uuid(),
    categoryId: 'health',
    amount: 200,
    spent: 85,
    month: currentMonth,
    createdAt: now.toISOString(),
  },
];

export const SAMPLE_GOALS: SavingsGoal[] = [
  {
    id: uuid(),
    name: 'Emergency Fund',
    targetAmount: 10000,
    currentAmount: 6500,
    deadline: '2026-12-31',
    icon: '🛡️',
    color: '#10B981',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: uuid(),
    name: 'Dream Vacation',
    targetAmount: 5000,
    currentAmount: 2200,
    deadline: '2026-08-01',
    icon: '✈️',
    color: '#3B82F6',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: uuid(),
    name: 'New Laptop',
    targetAmount: 2000,
    currentAmount: 1450,
    deadline: '2026-06-01',
    icon: '💻',
    color: '#8B5CF6',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: uuid(),
    name: 'House Downpayment',
    targetAmount: 50000,
    currentAmount: 12800,
    deadline: '2028-01-01',
    icon: '🏠',
    color: '#F59E0B',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
];
